### PR TITLE
Repackage (rename) zip files with old filename

### PR DESCRIPTION
**Pull request by nicolemah99**
This PR introduces a new script, `repackage-event-files.sh`, designed to repackage event files with the old filenames in  (`event_id.zip` and `event_id.zip.message`) system by unzipping, renaming, and re-zipping them according to a new naming convention. The script also includes a feature to skip files that already follow the new naming convention, allowing it to be run on directories that may contain both old and new file formats.

**New Naming Convention:** `location-data_type-meter-YYYYMM-id`
- **Examples:** 
  - kea-events-meter1-202401-12345.zip
  - kea-events-meter1-202401-12345.zip.message
- **Regex Check**: 
  -  Before processing each .message file, the script checks if the file matches the new naming convention using the regex pattern `^.*/[^/]+-[^/]+-[^/]+-[0-9]{6}-[0-9]+\.zip\.message$`. If a file matches this pattern, it is skipped, preventing unnecessary processing and allowing the script to be run on both file name formats.

**Usage:** `./repackage-event-files.sh <BASE_DIR>`
- Example `BASE_DIR`: camio-meter-stream/kea/events/level0

**Testing**:
I copy the data from `camio-psi-streams` to `ot-dev` and ran the script on it to rename/repackage and it was successful.

### CODE REVIEW

**Comment by nicolemah99** [comment]
@teknofire this is the old message file format, I noticed theres no level0 in the path and I would assume I should update the filename to the new zipfile name. Does that sound right?
```json
{
  "id": "10009",
  "filename": "10009.zip",
  "path": "KEA/events/2024-01/KOTZ-735-GEN_07",
  "data_type": "events"
}
```

**Comment by teknofire** [comment]
We should definitely fix the id/event_id and update the filename. 

For the path, I'm not sure we should actually have that now. That was something we needed when the mqtt message was being pushed from the kea side but now that the message is being transferred with the file the script that will read it in should determine the path to use itself instead. Also can we add the md5sum of the zip file in the message.

**Comment by nicolemah99** [comment]
Okay great, I created this issue for it and will work on that!
#183

**Comment by nicolemah99** [comment]
I've updated the scripts to updated the message files/content, it handles three different file versions:

For **V1** file, the script repackages (unzips, renames, zips, creates new message file) according to the new naming convention.
For **V2** files, the script updates the message file by removing the `path` field and adding the `md5sum` field.
For **V3** files, no action is needed as they are already in the most updated format.

**Message File Versions/Formats**

**V1**
```json
{
  "id": "10009",
  "filename": "kea-events-sel00-202406-10009.zip",
  "path": "kea/events/2024-06/sel00/10009",
  "data_type": "events"
}
```

**V2**
```json
{
  "event_id": "10009",
  "filename": "kea-events-sel00-202406-10009.zip",
  "path": "kea/events/2024-06/sel00/10009",
  "data_type": "events"
}
```

**V3 **
```json
{
  "event_id": "10009",
  "filename": "kea-events-sel00-202406-10009.zip",
  "md5sum": "12345678901234567890qwerty",
  "data_type": "events"
}
```

**Review by teknofire — APPROVED** [review]
:shipit:

**Comment by nicolemah99** [comment]
Added summary (tested on different data sets)

```bash
Summary of Processed Message Formats:

Version    Count               
-------    -----               
V1         35                  
V2         18                  
V3 (skipped) 64   
```

```bash
Summary of Processed Message Formats:

Version    Count               
-------    -----               
V1         35                  
V2         0                   
V3 (skipped) 82   
```

```bash
Summary of Processed Message Formats:

Version    Count               
-------    -----               
V1         0                   
V2         0                   
V3 (skipped) 117    
```

**Pull request merged**
